### ISSUE TITLE
Add a `LogDensityProblemAD` extension so we can support Turing

### ISSUE THREAD

**Issue by yebai** [withbayes/Tapir.jl#95] opened 2024-03-22 17:31 UTC
Let's create a `LogDensityProblemAD`extension within `Taped.jl`. That should enable us to play with more Turing models before this package gets officially registered. 

See, e.g.: https://github.com/tpapp/LogDensityProblemsAD.jl/blob/master/ext/LogDensityProblemsADZygoteExt.jl

**Comment by willtebbutt** [comment] 2024-05-01 10:51
I'll look at incorporating this in the near future.

**Comment by gdalle** [comment] 2024-05-01 12:24
I've been meaning to do a LogDensityProblemsAD PR that switches everything to ADTypes + DifferentiationInterface

**Comment by willtebbutt** [comment] 2024-05-01 12:35
> I've been meaning to do a LogDensityProblemsAD PR that switches everything to ADTypes + DifferentiationInterface. Maybe this is a sign

I, for one, would be in favour of having fewer things to maintain.

**Comment by gdalle** [comment] 2024-05-01 15:13
Well here you go: https://github.com/tpapp/LogDensityProblemsAD.jl/pull/29

**Comment by gdalle** [comment] 2024-05-01 16:04
If either of you can spare the time to review, it might help Tamas who is not familiar with DI (and me who is not familiar with Turing and its inner workings ^^)

**Comment by torfjelde** [comment] 2024-05-08 10:48
Does Tapir.jl not work with `VarInfo`?

**Comment by willtebbutt** [comment] 2024-05-08 11:51
I've only really tested it with `SimpleVarInfo` because I assumed it was easy for users of Turing to specify using `SimpleVarInfo`. Since it's not really, I need to get it working with `VarInfo` really.

**Comment by gdalle** [comment] 2024-05-08 13:07
The PR to LogDensityProblemsAD is nearly complete if you wanna help

**Comment by torfjelde** [comment] 2024-05-08 14:32
When you're talking about `SimpleVarInfo`, do you mean specifically the one using a `NamedTuple` under the hood @willtebbutt ?

>I've only really tested it with SimpleVarInfo because I assumed it was easy for users of Turing to specify using SimpleVarInfo. Since it's not really, I need to get it working with VarInfo really.

Even if we allow switching, `SimpleVarInfo` using a `NamedTuple` is more restricftive in what it can handle automatically.

It's also just a thing where `SimpleVarInfo` is not properly compatible with many models. For example, if I have a model like the following:
```julia
@model function demo()
    x = Vector{Float64}(undef, 2)
    x[1:2][:][1] ~ Normal()
    x[2] ~ Normal()
end
```
reconstructing this in a way that is compatible with `SimpleVarInfo` using a `NamedTuple` is very non-trivial since in Turing.jl, we only really see the stuff involved in a `~` statement, and not the other stuff.

**Comment by torfjelde** [comment] 2024-05-08 14:34
> If either of you can spare the time to review, it might help Tamas who is not familiar with DI (and me who is not familiar with Turing and its inner workings ^^)

Other than the Julia compat issue mentioned by @devmotion, Turing.jl doesn't really need much here I think:) As in, it doesn't "really matter" for Turing.jl what LogDensityProblemsAD.jl uses under the hood, as long as ADTypes.jl is still the way to specify which backend to use :+1:

**Comment by gdalle** [comment] 2024-05-08 14:57
I know, and I fixed the Julia compat issue (with a lot of blood, sweat and tears). My main issue now is convincing Turing people than the switch to DI is a good idea ^^

**Comment by devmotion** [comment] 2024-05-08 15:17
As @torfjelde said, for Turing it does not matter what LogDensityProblemsAD is doing under the hood (if it does not cause any regressions) as long as the API and compatibilities are not broken.

**Comment by gdalle** [comment] 2024-05-08 16:10
I did my best to keep them working in that PR, so hopefully this won't be a problem

**Comment by gdalle** [comment] 2024-05-08 16:23
But come to think of it, it would be nice to have downstream tests. Maybe I can open a Turing PR that uses this new branch of LogDensityProblemsAD, just to see what might break?

**Comment by torfjelde** [comment] 2024-05-09 17:55
> It would be good to focus efforts on making SimpleVarInfo feature parity with VarInfo, e.g. through https://github.com/TuringLang/DynamicPPL.jl/pull/555, rather than keeping spending more time dealing with VarInfo issues.

This is probably best discussed in a separate issue. But I don't think Tapir.jl will work with the `VarNameVector` approach if it doesn't work with the current `VarInfo`.

What's the actual reason for why Tapir.jl doesn't work with `VarInfo`?

**Comment by willtebbutt** [comment] 2024-05-13 08:14
> What's the actual reason for why Tapir.jl doesn't work with VarInfo?

The current reason (I _think_) is Tapir's lack of suppport for `Core._apply_iterate` -- but I'll only really know once I've got it working. Either way, I'm definitely pushing towards supporting `VarInfo`.

> When you're talking about SimpleVarInfo, do you mean specifically the one using a NamedTuple under the hood @willtebbutt ?

I suspect so -- I'm guessing we don't get type stability with the `Dict` approach?

**Comment by willtebbutt** [comment] 2024-05-13 18:38
I'm closing this in favour of #132 as I believe we've covered all of the ground that is Tapir.jl-specific. Please do re-open if you think I'm missing something!

**Closed by willtebbutt** 2024-05-13 18:38 UTC
Labels: enhancement, enhancement (testing)
